micronaut:
  application:
    name: connector
  server:
    port: ${APPLICATION_SERVER_PORT:7788}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

connector:
  pipelines:
    - name: "MyPipeline"
      source:
        type: FileSource
        config:
          path: "src/test/resources/observer-0.6.5/testfiles"
      decoder:
        type: AvroDecoder
      buffer:
        maxItems: 100
        maxWaitingTimeInS: 10
      sink:
        type: LoggerSink