= ObserveRTC Developer Manual: WebRTC Report Connector Service
balazs@observertc.org

The service is built to process {WebRTC-Reports}[TODO: Link].

== Build

This project requires Java 11 (min) and you can build it executing the following command:

[source,console]
----
./gradlew build
----

== Architecture

When you document your architecture you can use different `diagrams` blocks as
for example `plantuml`

[plantuml]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

== Implementation

Remember you can include piece of code extracted from your project using the `include` directive

    include::{sourcedir}/com/mycompany/service/MyService.java[tags=init]

== Pipeline Configurations

The connector executes pipelines under the hood, where each pipeline
describes a sequential set of operations should have applied on the consumes data.

An example configuration for a pipeline is given below:

