/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.observertc.webrtc.schemas.reports;
/** State of the Media */
@org.apache.avro.specific.AvroGenerated
public enum MediaType implements org.apache.avro.generic.GenericEnumSymbol<MediaType> {
  AUDIO, VIDEO, UNKNOWN, NULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MediaType\",\"namespace\":\"org.observertc.webrtc.schemas.reports\",\"doc\":\"State of the Media\",\"symbols\":[\"AUDIO\",\"VIDEO\",\"UNKNOWN\",\"NULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
